### ISSUE TITLE
牛客报名队伍名可能出错

### ISSUE THREAD

**Issue by Beater-w** [Core-65536/NowCoder_Balloon#1]
如题，你决不能说可爱的参赛者们手动报名的时候不会把队伍名填错
管理方的座位表是绝对正确的，但这个可能会跟选手填的会对不上

**Comment by Core-65536** [comment]
你说得对
我决定在下次更新中添加这个功能
只需要把原来传的(name,pid):1改成(uid,pid):1
然后在导入队列时做一个uid2name的转换
接着把座位导入改成uid2Seat
应该就大功告成了
